markdown: kramdown
highlighter: rouge
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""

repository: https://github.com/apache/orc
destination: target
exclude: [README.md,Gemfile*]
keep_files: [.git]

collections:
  docs:
    output: true
